env:
  browser: true
  es2021: true
  node: true
  jquery: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jquery
rules:
  "no-undef": ["error", { "typeof": false }]
  "jquery/no-undef": "off"
