version: 2.1
jobs:
  readme:
    docker:
      - image: mikohei/textlint:latest
    working_directory: ~/ToC1Kwin
    steps:
      - checkout
      - run:
          name: Check README.md
          command: |
            textlint --preset ja-technical-writing README.md
            textlint --preset preset-ja-spacing README.md
            textlint --rule spellcheck-tech-word README.md
            textlint --preset textlint-rule-preset-jtf-style README.md
  syntax_check:
    docker:
      - image: circleci/node:latest
    working_directory: ~/ToC1Kwin
    steps:
      - checkout
      - run: npm install
      - run:
          name: HTML syntax check
          command: npx htmlhint ./**/*.html
      - run:
          name: JavaScript syntax check
          command: npx eslint ./**/lint/*.js
          env:
            - "NODE_OPTIONS=--require eslint-plugin-jquery"
      - run:
          name: CSS syntax check
          command: npx stylelint ./**/lint/*.css
workflows:
  version: 2
  build:
    jobs:
      - readme:
          filters:
            branches:
              ignore:
                - main
      - syntax_check:
          filters:
            branches:
              ignore:
                - main
